"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Customer_1 = require("./Customer");
let myCustomer = new Customer_1.Customer("Landon", "Young");
console.log(myCustomer.firstName);
console.log(myCustomer.lastName);
console.log(myCustomer.fullName);
myCustomer.firstName = "BoJack";
myCustomer.lastName = "Horseman";
console.log(myCustomer.firstName);
console.log(myCustomer.lastName);
console.log(myCustomer.fullName);
