var found = true;
var grade = 88.6;
var firstName = "Landon";
var lastName = "Young";
found = 0;
grade = "A";
firstName = false;
console.log(found);
console.log("The grade is: " + grade);
console.log("Hi ".concat(firstName, " ").concat(lastName));
